[package]
name = "quorumdb-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.28.0", features = ["full"] }
quorumdb-core = { path = "../quorumdb-core" }
serde_json = "1.0.149"
serde = { version = "1.0", features = ["derive"] }
