[package]
name = "quorumdb-core"
version = "0.1.0"
edition = "2024"

[dependencies]
parking_lot = "0.12.5"
tokio = { version = "1.49.0", features = ["fs", "io-util", "rt", "sync"] }
rmp-serde = "1.3"
serde = { version = "1.0.228", features = ["derive"] }
